name: Deploy to Caprover

on:
  registry_package:
    types: [published]

env:
  IMAGE_NAME: "harbor.kub3.dev/kub3dev/confeitaria"

jobs:
  build-and-deploy:
    name: Change image version on CD
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Checkout CD repo
        uses: actions/checkout@v3
        with:
          repository: github.com/kub3dev/devops.git
          ref: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "deploy@kub3.dev"
      - name: commit changes
        run: |
          cd apps/production/confeitaria
          sed -E -i.bak 's%(${{ env.IMAGE_NAME }}:).*%${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version}}%' deployment.yaml
          git add .
          git commit -m "chore: deploy v${{ steps.package-version.outputs.current-version}}"
      - name: push changes
        run: git push origin main
