name: Docker Image
on:
  release:
    types: [published]

  # This workflow dispatch, allows us to execute this workflow manually
  workflow_dispatch:

env:
  IMAGE_NAME: "harbor.kub3.dev/kub3dev/confeitaria"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: version dockerfile
        uses: docker/setup-buildx-action@v3
      - name: log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.kub3.dev
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: push to Github Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.nixpacks/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version}}
            ${{ env.IMAGE_NAME }}:latest
